### ISSUE TITLE
printf segfaults with many string arguments

### ISSUE THREAD

**Issue by aifia** [kai-language/kai#126]
Using printf with more than one argument causes segmentation fault on linux. Am I doing something wrong or is it a bug. Here is an example code:
```
#import kai("posix")

Metadata :: struct {
    PKG: string
    VER: string
}

main :: fn() -> void {
    INF :: [2]string {"apkg", "0.14.0"}

    meta := Metadata {INF[0], INF[1]}

    posix.printf("%s %s\n".raw, meta.PKG, meta.VER)
}
```

**Comment by vdka** [comment]
Like with the strong literal you,will want to use the `.raw` field. Strings are currently stored as: 
```
string :: struct {
  raw: rawptr
  len: u64
  cap: u64
}
```
Because you’re calling to the Libc printf you have to make sure your strong is null terminated, which it will be in this case. Any constant initialised from a string literal will be null terminated.

**Comment by aifia** [comment]
It makes sense. Now printf works, thanks!
