### ISSUE TITLE
Dereference with subscript gets turned into if statement

### ISSUE THREAD

**Issue by BrettRToomey** [kai-language/kai#41]
# arrays.kai
```
 24 append_stringArray :: (array: *Array_string, value: string) -> void {
 25     if array.length >= array.capacity {
 26         expand_stringArray(array)
 27     }
 28 
 29     <array.data[int(array.length)] = value
 30     array.length += 1
 31 } 
```

For some reason, line #29 gets turned into an `if` statement. Here are the error messages:
```
 === Starting Checking === 

There were 3 errors during checking
exiting
ERROR(arrays.kai:25:5): Unexpected statement, expected expression
	raised by /Users/bretttoomey/Documents/kai/Sources/kai/Checker.swift:1604

ERROR(arrays.kai:29:38): Cannot use `value` (type string) as rvalue in assignment to `if leftChevron array.data[int(array.length)]` (type bool)
	raised by /Users/bretttoomey/Documents/kai/Sources/kai/Checker.swift:1581

```

**Comment by vdka** [comment]
Ah, the issue here is that `<` is being parsed as an infix operator.
A bad solution would possibly be to add a new state that says `parseNoFurther` which would drop the binding power of all infix operators to `0`.
I am sure there is a much nicer solution that would make use of the newline as a terminator.
More generally we need to make better use of newlines to terminate statements intelligently
