### ISSUE TITLE
Unconstrained Integer Conversion failing for array subscripts

### ISSUE THREAD

**Issue by BrettRToomey** [kai-language/kai#43]
Unconstrained Integer Conversion failing for array subscripts
  - ```
        for i : u8 = 0; i < 16; i += 1 {
            <buf[int(i)] = i
        }
    ```

  - Without explicit casts the above fails

**Comment by vdka** [comment]
The issue here needs a general solution for _`constraining`_ our unconstrained types if they are only used once as.
This can be fixed by adding a cast in the checker for `i` when used in the subscript. From there the IR Gen will automatically resize it to the desired size (I believe). This means whenever we see a subscript we should cast it to size we expect to need. Should be easy.

From memory a bigger issue arises if you change the code to:
```
for i := 0; i < 16; i += 1 {
    buf[i] = i
}
```
Where `= i` is not correctly constrained to the subtype of `buf`. Note that you also shouldn't need to use the `<` `deref` to deref anymore.
